function xstar = identification_el(x0, test, V0)

test(1, :) = test(1, :)-1;

options = optimoptions('fmincon', ...
                       'Algorithm', 'sqp', ...
                       'Display', 'iter-detailed', ...
                       'MaxIterations', 500, ...
                       'TolCon', 1e-10,...
                       'MaxFunctionEvaluations', 5000, ...
                       'OptimalityTolerance', 1e-8, ...
                       'StepTolerance', 1e-8, ...
                       'ConstraintTolerance', 1e-8, ...
                       'FiniteDifferenceType', 'central', ...
                       'FiniteDifferenceStepSize', 1e-8, ...
                       'Diagnostics', 'on');
[xstar,fxstar,k,exitflag,xsequence] = fmincon(@(x) cost_function(x, V0, test), x0,[],[],[],[],[0, 0],[100, 100],[],options);

R = xstar(1, 1);
L = xstar(2, 1);
modello = zeros(1, length(test));
for i = 1:length(test)
    modello(1, i) = V0/R*(1-exp(1)^(-(R/L)*test(1, i)));
end
figure()
plot(test(1, :), test(3, :))
hold on
plot(test(1, :), modello(1,:))
title(['Test ', num2str(V0), 'V'])
hold off