function k_mag_est = identification_km(k_mag0,x0, u, Tend_FFD, theta, test, Ts_FFD, titolo)

%% k_m identification
%cost = identification(k_mag, x0, u, Tend_FFD, theta, Test_21V)

options = optimoptions('fmincon', ...
                       'Algorithm', 'sqp', ...
                       'Display', 'iter-detailed', ...
                       'MaxIterations', 500, ...
                       'TolCon', 1e-10,...
                       'MaxFunctionEvaluations', 5000, ...
                       'OptimalityTolerance', 1e-8, ...
                       'StepTolerance', 1e-8, ...
                       'ConstraintTolerance', 1e-8, ...
                       'FiniteDifferenceType', 'central', ...
                       'FiniteDifferenceStepSize', 1e-8, ...
                       'Diagnostics', 'on');

[k_mag_est,fxstar,k,exitflag,xsequence] = fmincon(@(k_mag)identification(k_mag, x0, u, Tend_FFD, theta, test, Ts_FFD),k_mag0,[],[],[],[],[1e-7],[1e-4],[],options);



% Simulation using Forward Finite Differences
theta(2,1) = k_mag_est;
[t_FFD, x_FFD, ~ ] = FFD(Ts_FFD, Tend_FFD, x0, u, theta);

figure()
plot(t_FFD, x_FFD(1,:))
hold on
plot(test(1,:), test(2, :))
grid on
title(['Position, ', titolo])
hold off